[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
adminp = "FM2zDi5UkY3UqbZoVVF62KRcj6udk8H2kK14iduevuF5"
my_program = "CY79LabWnL8x2WFfu2PKYhhVwkVDdKtbFf3FoaAZzy9M"

[registry]
url = "https://api.apr.dev"

[programs.devnet]
adminp = "FM2zDi5UkY3UqbZoVVF62KRcj6udk8H2kK14iduevuF5"
my_program = "CY79LabWnL8x2WFfu2PKYhhVwkVDdKtbFf3FoaAZzy9M"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
